#!/bin/bash

# Summarise BLAST hits to only keep those reads with a positive hit
# for an expected species

HERE="$(dirname $0)"
TAXONOMY="${HERE}/../../taxonomy"

# samplesheet of sample BLAST result files (one per sample)
SAMPLESHEET="${HERE}/../inputs/blast_samplesheet.tsv"

# file with mappings of accessions to taxa
# (taxid, name and rank)
# this file can be generated by extracting the BLAST hit accessions
# and using something like taxonkit to translate to taxids
ACC2TAXMAP="${HERE}/../inputs/blast_taxmap.tsv"

cd ${HERE}/../../
mkdir -p results/summarise_blast
cd results/summarise_blast

TAXMAP=${PWD}/sorted.taxmap.tsv
sort -k 1,1 $ACC2TAXMAP > $TAXMAP

min_qlen=50
mkdir -p blast
mkdir -p summarised_blast
mkdir -p read_ids
mkdir -p tmp

echo "Discarding hits with query length < $min_qlen bp"
cut -f 2 $SAMPLESHEET | tail -n +2 \
	| xargs -n 1 -P 16 -I{} sh -c '
		out=blast/$(basename $1)
		awk -F "," -v minlen="$2" \
			"\$5 >= minlen" $1 \
		> $out
	' -- {} $min_qlen
echo "Done"

echo "Extracting read IDs from FASTA queries"
	cut -f 3 $SAMPLESHEET | tail -n +2 \
		| xargs -n 1 -P 16 -I{} sh -c '
			grep "^>" $1 \
			> read_ids/$(basename -s .fa $1).read_ids.txt
		' -- {}
echo "Done"

echo "Extracting reads with no BLAST hits"
# Get all reads with no blast hits
find blast -type f \
	| xargs -n 1 -P 16 -I{} sh -c '
		reads="read_ids/$(basename -s .blast $1).read_ids.txt"
		
		cut -d "," -f 1 "$1" \
			| uniq \
			| { fgrep -v -w -f - $reads || echo ""; }\
			> $(basename -s .blast $1).no_blast_hits.txt
	' -- {}
echo "Done"

echo "Summarising BLAST hit taxonomy to species level"
# Map sequence accessions to taxa summarised at the species level
find blast -type f \
	| xargs -n 1 -P 16 -I{} sh -c '
		blast_res=$1
		sample=$(basename $blast_res)
		taxmap=$2

		sort -t "|" -k 4,4 $blast_res \
			> tmp/${sample}.sorted

		cut -d "," -f 1 tmp/${sample}.sorted \
			> tmp/${sample}.read_ids

		cut -d "," -f 3- tmp/${sample}.sorted \
			> tmp/${sample}.blast_scores

		cut -d "|" -f 4 tmp/${sample}.sorted \
			> tmp/${sample}.accessions.sorted

		join tmp/${sample}.accessions.sorted $taxmap \
			| column -t -o "|" \
			| sed -e "s/\s//g" \
			| cut -d "|" -f 2- \
		> tmp/${sample}.taxa

		paste -d "," \
			tmp/${sample}.read_ids \
			tmp/${sample}.taxa \
			tmp/${sample}.blast_scores \
		> summarised_blast/${sample}
	' -- {} $TAXMAP
echo "Done"
